name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  coverage: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm run build
          npm test
          bash <(curl -s https://codecov.io/bash)
  e2e-angular-cli: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Create workspace
        run: npx -p @angular/cli@12 ng new ng-twelve-test-github-actions --create-application=false --strict
      - name: Create library
        run: npx -p @angular/cli@12 ng generate library my-lib
        working-directory: 'ng-twelve-test-github-actions'
      - name: Run action
        uses: ./
        with:
          code-coverage-threshold-branches: 100
          code-coverage-threshold-functions: 100
          code-coverage-threshold-lines: 100
          code-coverage-threshold-statements: 100
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          npm-dry-run: true
          npm-token: ${{ secrets.NPM_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          validate-dependencies: false
          working-directory: ./ng-twelve-test-github-actions
